./start-service.sh configuration-service
sleep 3
./start-service.sh logging-service
sleep 3
./start-service.sh users-service
sleep 3
./start-service.sh bitcoin-service
sleep 3
./start-service.sh validation-service
sleep 3
