./stop-service.sh configuration-service
sleep 3
./stop-service.sh logging-service
sleep 3
./stop-service.sh users-service
sleep 3
./stop-service.sh bitcoin-service
sleep 3
./stop-service.sh validation-service
sleep 3
